import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import { BrowserRouter } from "react-router-dom";
import { ConfirmProvider } from "./components/ConfirmDialog";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <BrowserRouter>
      <ConfirmProvider>
        <App />
      </ConfirmProvider>
    </BrowserRouter>
  </React.StrictMode>
);

// v4b10: the service worker is now generated by vite-plugin-pwa (Workbox) and registered by
// <PwaPrompts/> inside the staff + admin layouts, so the update prompt has something to hook.
// Registering it here as well would install it twice and race the two registrations.
